[fix #4] [mozmeao/infra#1104] Clean up oregon-b dev yaml.
mozmeao/basket-config pull request #14
Opened 2019-07-11 21:06 UTC by jpetto

- rename svc.yaml to web-svc.yaml

2019-07-12 16:38 UTC, jgmize requested changes
see comments on https://github.com/mozmeao/basket-config/pull/20 -- we need to make the same changes here and in the other PRs

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/donateworker-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/donateworker-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/ns.yaml
>  spec:
spec and status sections can be removed too

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/web-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/web-deploy.yaml
> +          value: 1
```suggestion
          value: "1"
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/web-deploy.yaml
> +          value: 0
```suggestion
          value: "0"
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/web-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/web-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/worker-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/worker-deploy.yaml
> +          value: 1
```suggestion
          value: "1"
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/worker-deploy.yaml
> +          value: 0
```suggestion
          value: "0"
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/worker-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 16:38 UTC, jgmize commented on oregon-b/basket-dev/worker-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-15 15:44 UTC, jpetto commented
@jgmize updated!

2019-07-16 17:48 UTC, jgmize approved these changes

2019-07-16 17:48 UTC, merged

2019-07-16 17:49 UTC, jgmize commented
thanks again @jpetto!