[fix #6] [mozmeao/infra#1104] Clean up oregon-b prod yaml.
mozmeao/basket-config pull request #17
Opened 2019-07-11 21:41 UTC by jpetto

- rename svc.yaml to web-svc.yaml

2019-07-12 21:15 UTC, jgmize requested changes

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/clock-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/clock-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/clock-deploy.yaml
> +          value: 587
```suggestion
          value: "587"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/clock-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/clock-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/clock-deploy.yaml
> +          value: 10
```suggestion
          value: "10"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/clock-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/clock-deploy.yaml
> +          value: 1
```suggestion
          value: "1"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/clock-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/donateworker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/donateworker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/donateworker-deploy.yaml
> +          value: 587
```suggestion
          value: "587"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/donateworker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/donateworker-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/donateworker-deploy.yaml
> +          value: 10
```suggestion
          value: "10"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/donateworker-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/donateworker-deploy.yaml
> +          value: 1
```suggestion
          value: "1"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/donateworker-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaeventsworker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaeventsworker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaeventsworker-deploy.yaml
> +          value: 587
```suggestion
          value: "587"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaeventsworker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaeventsworker-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaeventsworker-deploy.yaml
> +          value: 10
```suggestion
          value: "10"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaeventsworker-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaeventsworker-deploy.yaml
> +          value: 1
```suggestion
          value: "1"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaeventsworker-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaworker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaworker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaworker-deploy.yaml
> +          value: 587
```suggestion
          value: "587"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaworker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaworker-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/fxaworker-deploy.yaml
> +          value: 10
```suggestion
          value: "10"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/ns.yaml
>  spec:
Please remove the spec & status sections

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/web-deploy.yaml
> +          value: 587
```suggestion
          value: "587"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/web-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/web-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/web-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/web-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/web-deploy.yaml
> +          value: 10
```suggestion
          value: "10"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/web-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/web-deploy.yaml
> +          value: 1
```suggestion
          value: "1"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/web-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/web-svc.yaml
> +status:
Please remove the status section

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/worker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/worker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/worker-deploy.yaml
> +          value: 587
```suggestion
          value: "587"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/worker-deploy.yaml
> +          value: 5
```suggestion
          value: "5"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/worker-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/worker-deploy.yaml
> +          value: 10
```suggestion
          value: "10"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/worker-deploy.yaml
> +          value: 4
```suggestion
          value: "4"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/worker-deploy.yaml
> +          value: 1
```suggestion
          value: "1"
```

2019-07-12 21:15 UTC, jgmize commented on oregon-b/basket-prod/worker-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-22 17:25 UTC, jpetto commented
@jgmize okay, this should be ready for final review. apologies for missing those few original review comments.

2019-08-07 21:34 UTC, jgmize approved these changes
Thanks @jpetto

2019-08-07 21:34 UTC, merged