[fix #18] [mozmeao/infra#1104] update image hashes
mozmeao/basket-config pull request #19
Opened 2019-07-11 21:48 UTC by jpetto

2019-07-12 20:41 UTC, jgmize requested changes

2019-07-12 20:41 UTC, jgmize commented on frankfurt/basket-prod/clock-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-12 20:41 UTC, jgmize commented on frankfurt/basket-prod/web-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-12 20:41 UTC, jgmize commented on frankfurt/basket-prod/worker-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-12 20:41 UTC, jgmize commented on frankfurt/basket-stage/web-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-12 20:41 UTC, jgmize commented on frankfurt/basket-stage/worker-deploy.yaml
> +        image: mozmeao/basket:4d0668d
```suggestion
        image: mozmeao/basket:4d0668d4e5cb304e68b04bcc0d2b278d27b591e6
```

2019-07-15 16:59 UTC, jpetto commented
Closing in favor of #25

2019-07-15 16:59 UTC, closed without merging